export const RESEARCH_EVENT_NAMES = [
  "landing_viewed",
  "privacy_viewed",
  "test_route_viewed",
  "consent_viewed",
  "caregiver_setup_viewed",
  "preflight_viewed",
  "wearer_ready_viewed",
  "caregiver_inbox_viewed",
  "caregiver_review_viewed",
  "test_completion_viewed",
  "test_memolens_clicked",
  "see_how_it_works_clicked",
  "preorder_opened",
  "preorder_submitted",
  "preorder_submission_failed",
  "analytics_consent_accepted",
  "test_consent_completed",
  "test_consent_cancelled",
  "caregiver_setup_started",
  "routine_saved",
  "prompt_previewed",
  "voice_prompt_recorded",
  "preflight_started",
  "camera_permission_granted",
  "camera_permission_denied",
  "microphone_permission_granted",
  "microphone_permission_denied",
  "test_armed",
  "run_test_now_started",
  "wearer_mode_entered",
  "recording_started",
  "announcement_played",
  "prompt_played",
  "prompt_repeated",
  "privacy_stop_used",
  "recording_completed",
  "recording_failed",
  "caregiver_mode_entered",
  "video_playback_started",
  "video_playback_completed",
  "video_review_skipped",
  "caregiver_disposition_selected",
  "research_observations_submitted",
  "test_closed",
  "recording_deleted",
  "session_cleared",
  "session_abandoned",
  "research_logging_failed",
] as const;

export type ResearchEventName = (typeof RESEARCH_EVENT_NAMES)[number];

export const ANALYTICS_EVENT_HEADERS = [
  "schema_version",
  "event_id",
  "session_id",
  "sequence_number",
  "occurred_at_utc",
  "received_at_utc",
  "event_name",
  "page_path",
  "role_mode",
  "workflow_step",
  "cta_id",
  "source",
  "elapsed_ms",
  "device_type",
  "browser_family",
  "os_family",
  "language",
  "timezone",
  "online",
  "analytics_consent_version",
  "properties_json",
] as const;

export const TEST_SESSION_HEADERS = [
  "schema_version",
  "session_id",
  "participant_code",
  "participant_type",
  "test_condition",
  "started_at_utc",
  "ended_at_utc",
  "received_at_utc",
  "completion_state",
  "furthest_step",
  "zero_touch_success",
  "wearer_interaction_count",
  "prompt_type",
  "prompt_delivered",
  "prompt_repeat_count",
  "camera_permission",
  "microphone_permission",
  "recording_status",
  "recording_duration_seconds",
  "recording_blob_bytes",
  "privacy_stop",
  "video_review_status",
  "caregiver_review_started_at_utc",
  "review_duration_seconds",
  "caregiver_disposition",
  "clip_usefulness",
  "prompt_comprehension",
  "false_reassurance",
  "review_burden",
  "privacy_rating",
  "technical_error_code",
  "research_notes",
  "research_consent_version",
  "submitted_at_utc",
] as const;

export const LEAD_HEADERS = [
  "schema_version",
  "lead_id",
  "submitted_at_utc",
  "received_at_utc",
  "name",
  "phone_country_code",
  "phone_number",
  "role_interest",
  "source_cta",
  "contact_consent",
  "consent_text_version",
] as const;

export const INGESTION_ERROR_HEADERS = [
  "schema_version",
  "received_at_utc",
  "request_id",
  "error_code",
  "error_message",
  "payload_type",
  "session_id",
] as const;

